### ISSUE TITLE
Misleading bus schedule

### ISSUE THREAD

**Issue by adsk3003** [iith-dashboard/IITH-Dashboard-frontend#3]
**Describe the bug**
Shows weekday schedule during weekends when you open complete bus schedule and weekend is highlighted and you need to click on weekend to get the correct schedule.

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch the app during weekends.
2. Open complete bus schedule.
3. Click on weekend to get the correct schedule.

**Expected behaviour**
It should show weekend schedule

**Screenshots**
![Screenshot_20191012-111406_IITH_DashBoard](https://user-images.githubusercontent.com/44468736/66695718-92baf200-ece2-11e9-9aaa-a7d118884f47.png)
![Screenshot_20191012-111349_IITH_DashBoard](https://user-images.githubusercontent.com/44468736/66695719-92baf200-ece2-11e9-8377-e8ed6375c89d.png)
![Screenshot_20191012-111358_IITH_DashBoard](https://user-images.githubusercontent.com/44468736/66695720-93538880-ece2-11e9-953d-1480c6920fc1.png)

**Smartphone (please complete the following information):**
 - Device: [Redmi Note 5 Pro]
 - OS: [Android Pie (9.0) (custom ROM)]

**Comment by aayush2710** [comment]
The issue has been fixed in the latest version
