### ISSUE TITLE
Possible to schedule clashing courses manually through the app

### ISSUE THREAD

**Issue by RachitKeertiDas** [iith-dashboard/IITH-Dashboard-frontend#5]
**Describe the bug**

While adding courses in the timetable manually(through the App), it is possible to add two clashing courses.  

**To Reproduce**
1. Go to Timetable Section of the App
2. Click on the `+` button. 
3. Add a course manually in any slot.
4. Add another course in the same slot. Make sure the _second course_ overlaps and has a **longer duration**(i.e, is running for more segments).

**Expected behavior**
See a clashing course message. The overlapping course is not added.

**Actual Behavior**
The second course gets added and overlaps with the shorter course. On deleting the second course, the first course reappears in the timetable.

**Smartphone:**
 - Device: Xiaomi Redmi  7S
 - OS: Android Pie (9.0)

**Additional context**
This bug can be reproduced only when the *second* course has longer duration. A Course Clashes message is received if the first course has longer duration.

**Comment by angad11121** [comment]
Bug also possible for 2 credit courses with only 34 segment as an intersection
